const initialDetails = [
    {
      id: 1,
      imgPath: "/assets/img/1.jpg",
      name: "Jane Doe",
      email: "janedoe@gmail.com",
      address: "New Delhi, India",
    },
    {
      id: 14,
      imgPath: "/assets/img/1.jpg",
      name: "Jane Doe",
      email: "janedoe@gmail.com",
      address: "New Delhi, India",
    },
    {
      id: 15,
      imgPath: "/assets/img/1.jpg",
      name: "Jane Doe",
      email: "janedoe@gmail.com",
      address: "New Delhi, India",
    },
    {
      id: 2,
      imgPath: "/assets/img/2.jpg",
      name: "Mary Rosamund",
      email: "agra@rosie.com",
      address: "Tbilisi, India",
    },
    {
      id: 3,
      imgPath: "/assets/img/3.jpg",
      name: "Sherlock Watson",
      email: "irene@johnlock.com",
      address: "Baker Street, India",
    },
    {
      id: 4,
      imgPath: "/assets/img/4.jpg",
      name: "John Holmes",
      email: "mary@johnlock.com",
      address: "Baker Street, India",
    },
    {
      id: 5,
      imgPath: "/assets/img/5.jpg",
      name: "Mycroft Lestrade",
      email: "britishgovt@gmail.com",
      address: "London, India",
    },
    {
      id: 6,
      imgPath: "/assets/img/5.jpg",
      name: "Mycroft Lestrade",
      email: "britishgovt@gmail.com",
      address: "London, India",
    },
    {
      id: 7,
      imgPath: "/assets/img/5.jpg",
      name: "Mycroft Lestrade",
      email: "britishgovt@gmail.com",
      address: "London, India",
    },
    {
      id: 8,
      imgPath: "/assets/img/5.jpg",
      name: "Mycroft Lestrade",
      email: "britishgovt@gmail.com",
      address: "London, India",
    },
    {
      id: 9,
      imgPath: "/assets/img/5.jpg",
      name: "Mycroft Lestrade",
      email: "britishgovt@gmail.com",
      address: "London, India",
    },
    {
      id: 10,
      imgPath: "/assets/img/5.jpg",
      name: "Mycroft Lestrade",
      email: "britishgovt@gmail.com",
      address: "London, India",
    },
    {
      id: 11,
      imgPath: "/assets/img/5.jpg",
      name: "Mycroft Lestrade",
      email: "britishgovt@gmail.com",
      address: "London, India",
    },
    {
      id: 12,
      imgPath: "/assets/img/5.jpg",
      name: "Mycroft Lestrade",
      email: "britishgovt@gmail.com",
      address: "London, India",
    },
    {
      id: 13,
      imgPath: "/assets/img/5.jpg",
      name: "Mycroft Lestrade",
      email: "britishgovt@gmail.com",
      address: "London, India",
    },
];

export default initialDetails;
  